image: python:3.9

cache:
  paths:
    - /root/.local/bin/poetry

variables:
  coverage_report_view: "true"

before_script:
  - test -e $HOME/.poetry/bin/ || curl -sSL https://install.python-poetry.org | python -
  - export PATH="/root/.local/bin:$PATH"
  - poetry install
  - poetry --version
      
stages:
  - lint
  - test

lint-test-job:
  stage: lint
  script:
    - echo "Linting code..."
    - poetry run isort .
    - poetry run black .
    # remove linting for now - poetry run pylint lawinprogress/

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - poetry run coverage run -m pytest tests/
    - poetry run coverage report
    - poetry run coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./coverage.xml